gesdinet_jwt_refresh_token:
  # user_provider: security.user.provider.concrete.app_user_provider
  refresh_token_class: App\Entity\RefreshToken
  single_use: true
  # Le refresh token est valide 3 jours (259200 secondes)
  ttl: 259200
